name: volks_demo
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  intl: ^0.16.1
  floor: ^0.14.0
  dropdown_formfield: ^0.1.3
  flutter_datetime_formfield: ^0.1.2
  flutter_search_bar: ^2.1.0
  image_picker: ^0.6.7+12



  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.14.0
  build_runner: ^1.7.3

flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf